[project]
name = "rasp-pi-projects"
version = "0.0.1"
requires-python = ">=3.10"
dependencies = [
    "numpy"
]

[project.optional-dependencies]
dev = [
    "pre-commit>=4.3.0"
    "ruff>=0.14.3",
]

[tool.ruff]
line-length = 89

[tool.ruff.format]
docstring-code-format = true

[tool.ruff.lint]
# set of enabled rules controlled via select, extend-select, ignore
extend-select = ["E501", "D"]

[tool.ruff.lint.pydocstyle]
convention = "google"